### ISSUE TITLE
Theme

### ISSUE THREAD

**Issue by soto0** [SmitAkbari26/HollowDark#2]
Hello, I really liked your hollowDark theme, but as I see you updated it. Could you also upload the previous version in vs code?)

**Comment by SmitAkbari26** [comment]
I will make Hollow, Hollow Dark as two theme inside one Hollow Dark is one that you liked and Hollow is theme which i update it.

**Comment by SmitAkbari26** [comment]
Hello @soto0,
i will update theme now you can use both the theme which you like.
If any query or don't like about theme just make issue so i can solve it.
Thank you.
